/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface': '#2c2f30',
        'on-secondary-container': '#7b3100',
        'inverse-surface': '#0c0f10',
        'tertiary-container': '#00e3fd',
        'on-error-container': '#520c00',
        'secondary-fixed': '#ffc5aa',
        'inverse-on-surface': '#9b9d9e',
        'inverse-primary': '#ffd709',
        'surface-variant': '#dadddf',
        'on-tertiary-fixed': '#003840',
        'on-primary-container': '#5b4b00',
        'on-surface-variant': '#595c5d',
        'tertiary': '#006571',
        surface: '#f5f6f7',
        'tertiary-fixed': '#00e3fd',
        'primary-fixed': '#ffd709',
        'surface-dim': '#d1d5d7',
        'outline-variant': '#abadae',
        background: '#f5f6f7',
        'error-container': '#f95630',
        'secondary-dim': '#883700',
        error: '#b02500',
        'surface-container-lowest': '#ffffff',
        'on-background': '#2c2f30',
        'primary-dim': '#5e4e00',
        'secondary-container': '#ffc5aa',
        'on-primary-fixed': '#453900',
        'on-error': '#ffefec',
        'on-secondary-fixed': '#5c2300',
        'on-secondary-fixed-variant': '#893700',
        'tertiary-fixed-dim': '#00d4ec',
        'surface-container-low': '#eff1f2',
        'on-tertiary': '#d8f8ff',
        'primary-container': '#ffd709',
        'primary-fixed-dim': '#efc900',
        'on-primary': '#fff2cd',
        secondary: '#9b3f00',
        'error-dim': '#b92902',
        outline: '#757778',
        'surface-container-highest': '#dadddf',
        'secondary-fixed-dim': '#ffb28c',
        'on-tertiary-container': '#004d57',
        'surface-container': '#e6e8ea',
        'surface-container-high': '#e0e3e4',
        'surface-tint': '#6c5a00',
        'on-tertiary-fixed-variant': '#005762',
        'on-primary-fixed-variant': '#665500',
        'on-secondary': '#fff0ea',
        primary: '#6c5a00',
        'surface-bright': '#f5f6f7',
        'tertiary-dim': '#005863',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Be Vietnam Pro', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
